[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
async-trait = { workspace = true }