[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
service-protos = { path = "../service-protos" }
async-trait = { workspace = true }