[package]
name = "http-service"
version.workspace = true
edition.workspace = true

[[bin]]
name = "file_server"
path = "src/file_server.rs"
doc = false

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
actix-multipart = "0.7.2"
env_logger = "0.11.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { workspace = true, features = ["full"] }