name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Checks:
    name: checks

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install-requirements
      run: ./scripts/install_requirements.sh
    - name: Run cargo test --verbose
      run: cd file-service; cargo test --verbose
    - name: Run cargo clippy --all-targets -- -D warnings
      run: cd file-service; cargo clippy --all-targets -- -D warnings
    - name: Run cargo clippy --all-targets --all-features -- -D warnings
      run: cd file-service; cargo clippy --all-targets --all-features -- -D warnings
    - name: Run rustup toolchain install nightly --component rustfmt
      run: rustup toolchain install nightly --component rustfmt
    - name: Run cargo +nightly fmt --all -- --check --files-with-diff
      run: cd file-service; cargo +nightly fmt --all -- --check --files-with-diff

  Build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install-requirements
        run: ./scripts/install_requirements.sh
      - name: Build
        run: cd file-service; cargo build --verbose
